#ifndef INCLUDE_SRC_ADDRESSING_H_
#define INCLUDE_SRC_ADDRESSING_H_

typedef enum AddressingMode {
  AM_ACCUMULATOR,
  AM_ABSOLUTE,
  AM_ABSOLUTE_X,
  AM_ABSOLUTE_Y,
  AM_IMMEDIATE,
  AM_IMPLIED,
  AM_INDIRECT,
  AM_INDIRECT_X,
  AM_INDIRECT_Y,
  AM_RELATIVE,
  AM_ZERO_PAGE,
  AM_ZERO_PAGE_X,
  AM_ZERO_PAGE_Y,
} AddressingMode;

#endif // INCLUDE_SRC_ADDRESSING_H_
